### ISSUE TITLE
ko -> kr 이전 및 기타 이슈

### ISSUE THREAD

**Issue by goldmetal** [StonehearthForum/stoneHearth_locale_kr#1]
다시 만나뵙게 되어 반갑습니다.

먼저 kr로 순조롭게 이전해주셔서 감사합니다.
머지도 깔끔하게 해주셨네요.

앞으로는 여기서 활동하도록 유도 하겠습니다.
(기존 ko는 진행사항 모두 Close.)

그리고 말랑님이 갑자기 조직에서 나가셨는데
혹시 문제가 있어서 나가신건지요?

**Comment by ghost** [comment]
이제 사용하지 않는 계정이라서 지웠습니다 앞으로는 이 계정으로만 활동할 예정이에요.

**Comment by ghost** [comment]
## 작업1
- [x] 기존 기여자 커밋메시지 추가
- [x] 등록된 프로젝트 이전
- [x] 등록된 이슈 이전
- [x] 등록된 PR 이전
- [x] label 변경

**Comment by goldmetal** [comment]
정리 감사합니다.
이 이슈는 닫겠습니다.
