### ISSUE TITLE
ui.game.build_mode.building_templates.template_names, data.tutorial.tutorial_steps

### ISSUE THREAD

**Issue by jine0th** [StonehearthForum/stoneHearth_locale_kr#11]
#5 
ui.game.build_mode.building_templates.template_names
data.tutorial.tutorial_steps

진행하겠습니다.

**Comment by goldmetal** [comment]
감사합니다.
그리고 포크하신건 지우시고, 기존에 하던 방식 그대로 하시면 됩니다.
괜히 힘들게 절차만 늘리는 것 같아서요.
죄송합니다.

**Comment by jine0th** [comment]
아닙니다. 그렇게 하도록 할게요 ㅎㅎ

**Comment by jine0th** [comment]
아닙니다. 그렇게 하도록 하겠습니다! 
그런데 제가 포크한거 잘 지운거 맞죠? ㅎㅎ....

**Comment by goldmetal** [comment]
네, 포크된 레포는 개인의 것이기 때문에 마스터 레포와는 무관합니다.
저도 지웠는걸요.

**Comment by ghost** [comment]
번역 완료 커밋하셔서 close하겠습니다.  커밋메시지에 Close [이슈번호] 형식으로 바로 닫으실 수 있으니 완료한 후에 '번역완료, Close #11' 이런형식으로 뒤나 앞에 붙여주시면 자동으로 닫으실 수 있습니다.
