### ISSUE TITLE
 data.shops.basic_resource_shop

### ISSUE THREAD

**Issue by creamizzing** [StonehearthForum/stoneHearth_locale_kr#13]
#5 번역 진행 합니다.

**Comment by creamizzing** [comment]
번역 완료

**Comment by goldmetal** [comment]
완료하셨다면 이슈 닫으시면 됩니다~

**Comment by ghost** [comment]
번역 완료 커밋하셔서 close하겠습니다. 커밋메시지에 Close [이슈번호] 형식으로 바로 닫으실 수 있으니 완료한 후에 '번역완료, Close #13' 이런형식으로 뒤나 앞에 붙여주시면 자동으로 닫으실 수 있습니다.
