### ISSUE TITLE
Oghar 는 오거에 여성형인가요?

### ISSUE THREAD

**Issue by creamizzing** [StonehearthForum/stoneHearth_locale_kr#15]
검색해도 안 나오네요

**Comment by goldmetal** [comment]
세계관은 좀 다르지만 단서가 되는 영문서를 확인하였습니다.
http://galnet.wikia.com/wiki/Oghar

문서에 따르면 오거 중에서도 강력함이 남달라서
오거 부족을 이끌어가는 소수종족이라고 하네요.
보스급 오거라고 생각하시면 되겠습니다.

오거 단어의 원산지는 프랑스이므로
프랑스 번역기로 돌려보니 "오우거"라고 읽혀지네요.

Ogre = 오거  , Oghar = 오우거
이렇게 하시면 될 것 같습니다.
이것은 프로젝트 사전에 추가하겠습니다.
https://github.com/StonehearthForum/stoneHearth_locale_kr/projects/1#card-2456265
