### ISSUE TITLE
릴리즈(태그) 건의

### ISSUE THREAD

**Issue by ghost** [StonehearthForum/stoneHearth_locale_kr#17]
릴리즈 전 태그 달 때 067719d647de7f7d8936b9c5aa6ff2e1dbdea1b9 아래 커밋과 같이 '버전만 변경한' 커밋을 하고 이 커밋에다가 태그해서 릴리즈하면 좋겠습니다.

**Comment by goldmetal** [comment]
좋은 생각입니다.
다음 릴리즈는 less까지 수정 완료하고,
최종적으로 말씀하신대로 버전만 올려서 커밋 한번 더 할께요.
