### ISSUE TITLE
마스터와 서브 브랜치 관리 방법

### ISSUE THREAD

**Issue by goldmetal** [StonehearthForum/stoneHearth_locale_kr#2]
이미 알파21 버전에서 일부 번역 작업이 마스터에서 이루어졌지만
앞으로는 이전과 마찬가지로 해당 버전의 브랜치를 새로 올려서 커밋하려고 합니다.
(2017.04.10 저녁에 생성 예정.)

문제는 그 다음인데,
현지화 팀이 작업하기 위해 레포를 새로 만들 때,
브렌치 형식으로 할지 포크 형식으로 할지 고민 중입니다.
(포크는 이전에 문제가 있었고 하니..)

**브렌치 방식**
Alpha21 브렌치에서 Alpha21_[닉네임] 형식의 개인의 branch를 따와서 작업.

**포크 방식**
Alpha21 브렌치를 개인의 Alpha21 브렌치를 개인의 레포로 포크한 뒤에 따로 작업.

이 뒤에는 
매주 한번씩 결산으로 Merge 한 뒤, 관리쪽에서 less 잡아준 뒤 릴리즈 하려 합니다.

어떤 것이 좋을까요?

**Comment by ghost** [comment]
fork 후 merge하는 편이 좋을 꺼 같습니다.

**Comment by goldmetal** [comment]
네, 그럼 그렇게 하도록 하지요~

**Comment by goldmetal** [comment]
오늘 퇴근하면서 생각해보았는데..
깃허브 처음 사용하시는 분에게 어렵기도하고 
무엇보다 이슈나 프로젝트 같은게 완전히 분리되어버려서
사용 자체가 힘들어질 것 같아서 그냥 알파 버전 브렌치에서
작업하는게 좋을 것 같습니다.

**Comment by ghost** [comment]
프로젝트랑 이슈랑은 같이 다닐 수 있습니다..,

**Comment by goldmetal** [comment]
포크할 때 따로 설정을 해줘야 하는건지요?
제가 포크했을대는 레포만 오고 그 둘은 안따라와서요.

**Comment by ghost** [comment]
fork해서 수정 한 후에 현 repo로 PR을 넣으면 됩니다.

현재 repo에서 new PullRequest > base fork: StoneHearthForum | head fork: MY REPO 선택 후 create pull request 하면 됩니다.

**Comment by goldmetal** [comment]
아, 제가 말씀드리는거는 현 레포 -> 개인 레포 로 fork할 때,
현 레포의 이슈, 프로젝트 정보가 같이 개인 레포로 들어가는 방법을 말씀드리는겁니다.

fork하는 순간, 살펴보아야할 레포 공간이 두 개가 되어버려서
그 번거로움을 말씀드리는거여요.

깃허브를 처음 만지시는 분들에게
너무 타이트한 형상 관리이지 않나 생각이 듭니다.
(뭣보다 만지는 파일이 ko.json 파일 하나뿐이라..)

이 맴버로 무시히 알파21 버전을 마치면
다음 22버전에서부턴 fork를 쓰는 방식으로 해보아요.

**Comment by ghost** [comment]
fork말고 현 레포에 바로 pr 넣는 방식으로 해도 괜찮을 꺼 같아요 :D

**Comment by goldmetal** [comment]
현 레포에서 PR로 하려면 개인 Branch를 만들어야겠죠?
Alpha21_Goldmetal 이라던가 아님 그냥 Goldmetal 이라던가

**Comment by ghost** [comment]
음 아 그런문제가 있군요. 만들게 된다면 번역 단위에 따라 만들고 완료되면 지우는 식으로 해야할 거 같아요. 이런식으로 https://www.atlassian.com/git/tutorials/comparing-workflows

**Comment by goldmetal** [comment]
번역단위의 Branch 좋네요.
그럼 오늘부터 점차 적용해보도록 하지요.
