### ISSUE TITLE
data.build.building_brushes

### ISSUE THREAD

**Issue by ghost** [StonehearthForum/stoneHearth_locale_kr#21]
#5 #33

**Comment by goldmetal** [comment]
슬슬 2분기 번역 파트 잡아보려 하는데
2분기로 넘기고 1분기 이슈는 클로즈하겠습니다.

**Comment by goldmetal** [comment]
혹지 진행된 부분이 있으면 그 부분만 업로드 부탁드리겠습니다.
나머지 미진행 부분은  같이 처리하던가 해요.
