### ISSUE TITLE
약초사 > 약제사로 바꾸는 건 어떨까요?

### ISSUE THREAD

**Issue by creamizzing** [StonehearthForum/stoneHearth_locale_kr#28]
어떨까요?

**Comment by goldmetal** [comment]
약제사도 좋지만 약간 현대적 느낌이 섞어있는 단어라
다른 분의 의견도 들어봐야 할 것 같습니다.
게다가 약제사는 아예 매치되는 다른 단어도 있구요. (a pharmacist)

제 개인적으로는 원래의 뜻 그대로 살린 약초사에 조금 쏠리네요.

**Comment by jine0th** [comment]
약제사(Pharmacist) vs 약초사(Herbalist)
비슷한 말인 줄 알았는데 찾아보니 생각보다 다른 부분이 많더군요.
찾아본 결과 게임 내에서의 기능이나 역할을 봤을 때 '약초사'라는 단어의 의미를 좀 더 강하게 지닌 것 같습니다.
건의해볼만한 사항이긴 하지만 저도 약초사 라는 단어에 표를 던지고 싶네요 ㅎㅎ

**Comment by creamizzing** [comment]
전 약초사 하면 심마니가 연상되서 제안했는데 약제사 뜻이 따로 있으니 고대로 가죠.
약초사 2단계 직업으로 약제사 나오면 좋겠네요

**Comment by ghost** [comment]
심마니 괜찮네요 ㅋㅋ

**Comment by goldmetal** [comment]
심마니 하니까 왠지 한국 한정 클래스 같네요 ㅋㅋㅋ

**Comment by ghost** [comment]
뭐 현지화라는 이름으로 심마니라고 해두 괜찬을꺼같은대요?ㅎㅎ

**Comment by goldmetal** [comment]
일단 그대로 유지한다는 의견이 많으므로 이 이슈는 닫도록 하겠습니다.
