### ISSUE TITLE
data.commands

### ISSUE THREAD

**Issue by jine0th** [StonehearthForum/stoneHearth_locale_kr#29]
#5 
너무 많네요 ㅠㅠ
일단 도전해봅니다.
![1](https://cloud.githubusercontent.com/assets/27216467/25011908/df5c444a-20a9-11e7-9e80-58e0b55b331e.png)
data.commands에 뭐있나 보다가 사진처럼 되어있는게 있던데요.
우선 오른쪽에 위치한 번역된 기준으로 했습니다.

**Comment by goldmetal** [comment]
아아, 오른쪽은 기존 알파15때의 파일 흔적입니다.
영문장일때는 무조건 왼쪽 오리지널 기준으로 작업해주세요.

**Comment by jine0th** [comment]
네 감사합니다. 그렇게 하도록 하겠습니다.
