### ISSUE TITLE
현지화 팀 확인 이슈

### ISSUE THREAD

**Issue by goldmetal** [StonehearthForum/stoneHearth_locale_kr#3]
스톤하스 한글 모드 팀에 오신 것을 환영합니다!

현지화 팀으로 초대 받으신 팀원께서는
여기에 간단한 인사 코멘트로 확인 부탁드립니다.
 
혹시 궁금하신 사항이 있으면 이쪽 번역 프로세스 마일스톤(milestone)에 이슈 (issue)를
새로 만드셔서 질문 올려주시면 되겠습니다.

**Comment by creamizzing** [comment]
안녕하세요 creamizzing 입니다. 저랩 영어지만 열심히 할게요!

**Comment by jine0th** [comment]
안녕하세요.

이번에 새로 들어온 김국진(jine0th)이라고 합니다.

잘 부탁드립니다.

대학생(현재 휴학중이지만...)이고

예전에 어플 번역에 조금 참여한 적이 있는데 많은 도움이 됐으면 좋겠습니다.

**Comment by ghost** [comment]
안녕하세요 처음으로 프로젝트 만들었던 프요라고 합니다. 다시 활성화되다니 열심히 해볼게요!

**Comment by 33wkdgns** [comment]
신참입니다!
실력은 뭐... 어쨋든!
여러 세세한 부분 (예를들어 아이템을 클릭하면 나오는 그런거..)들이라도 해석할려고 시도중입니다.
