### ISSUE TITLE
하나가 번역이 안되네요 ㅠ

### ISSUE THREAD

**Issue by jine0th** [StonehearthForum/stoneHearth_locale_kr#30]
어쩌다보니 해가 뜨네요... 하하핳... 암튼!!

#29 data.commands

Harvest(수확)에 대한 설명인Harvest for lumber, or just to get it out of the way. 부분 빼고는 완료했는데

이상하게 이 부분을 어떻게 해석해야할지 막막하네요.

그리고

Cid, Dania, Anwyn Redelm와 같은 사람들 이름의 경우 일단은 영어 그대로 했습니다. (사람 이름 맞나요...)

암튼 어차피 스톤하스 캐릭터도 이름은 다 영어인 것처럼요.

그리고 몬스터의 족장 역할인 Ogo가 있던데 이 역시 일단은 영어 Ogo로 그대로 뒀습니다.

Orge의 경우 오거, Oghar의 오우거인데 Ogo는 오고로 해야할지 몰라서 일단 영어 그대로 했습니다.

도움을 주셨으면 좋겠습니다.

**Comment by goldmetal** [comment]
나무를 제거하는 이유는 두가지인데 목재를 얻거나, 건설에 방해받을 때이지요.
그 이야기인 것 같습니다.

Cid, Dania 같은 단일 이름 명사는 그냥 소리나는 대로 번역하시면 되겠습니다.
(시드 , 데니아)
Anwyn Redelm 같은 풀 네임 사람 이름 경우는
일단 건너 뛰는게 좋을 것 같습니다.

그리고 Oghar를 좀 더 찾아봤더니 오우거 보다는 "오가르"가 더 정확하더군요.
(하스스톤에서도 '록타 오가르' 대사가 나옴.)
Ogo 는 그냥 단순하게 오고 라고 하는게 맞겠네요.
