### ISSUE TITLE
entities

### ISSUE THREAD

**Issue by jine0th** [StonehearthForum/stoneHearth_locale_kr#31]
#33 
entities 진행

**Comment by goldmetal** [comment]
이쪽은 데이터량이 상당히 많아서 세분화하려 합니다.
2분기를 이쪽으로 잡고 공지 올렸습니다만..
이미 엄청나게 진행하셔서 따로 새로운 이슈는 만들지 않으셔도 되겠습니다.

본문에 # 33 달아주시구, 진행하시는 대로 계속 해주시면 되겠습니다.
저도 인게임 테스트로 검수하면서 어색한 부분은 조금씩 잡아볼께요.

**Comment by Goldmetal** [comment]
혹시 지금 진행하고 계신 내용이 있으면 커밋해주시구
진행하시는 파트에 대해서 # 33 이슈 보시고 1분기처럼
이슈 올려주시면 감사하겠습니다.
