### ISSUE TITLE
자동화 시스템

### ISSUE THREAD

**Issue by ghost** [StonehearthForum/stoneHearth_locale_kr#32]
쉬운 관리 및 유효성 검사를 위해 자동화 시스템을 추가하려고 합니다. 추가됨에 따라 번역시 따로 달라지는 점은 없습니다.

## 추가될 기능
 - [ ] 업데이트 커밋 시 자동 릴리즈 및 태그 추가 기능
 - [ ] 번역 파일 및 ui 파일에 대한 유효성 검증

 ## 사용 도구
 - Travis CI
 - (필요할 시) NodeJS + Mocha

가끔 테스트 하다가 travis ci가 꼬일 때가 있어서  repo를 따로 만들어서 할 생각입니다.

kygn1998/stoneHearth_kr_travis_test

**Comment by goldmetal** [comment]
다른 분들이 커밋하실 때, 따로 프로세스가 추가되는 것인지요?

**Comment by ghost** [comment]
커밋이후 해당 커밋이 정상적으로 작동하는지 판단하는 부분입니다 

![#](https://github.com/kygn1998/test/raw/master/2017-04-24-003.png)
이런식으로 나옵니다

**Comment by goldmetal** [comment]
그림 파일인지 깨져서 나오네요 ㅠㅠ

**Comment by ghost** [comment]
![#](http://i.imgur.com/17GC0ow.png)
