### ISSUE TITLE
 entities.monsters

### ISSUE THREAD

**Issue by creamizzing** [StonehearthForum/stoneHearth_locale_kr#36]
번역 중입니다.
#33

**Comment by creamizzing** [comment]
Property of Central Chief Grug Skull Crusher
을 뭐라고 번역 해야 할 지 모르겠네요
중앙 씨족 대장 그렁 스쿨 크러셔?

**Comment by creamizzing** [comment]
위 항목 제외하고 #36은 전부 완료 했습니다.

**Comment by jine0th** [comment]
번역 잘 하셨네요 ㅎㅎㅎ 저도 못하는 편이라 뭐라 할 입장은 아니지만요..
General's Hat 해석을 장군 모자라고 하셨던데, 장군의 모자라고 하는게 좀 더 자연스러울 것 같아요. ㅠ

그리고 Property of Central Chief Grug Skull Crusher에 대해서는
Tag name을 보시면 goblin cage에 대한 description이더군요.
Central 족장 그러그 스컬 크러셔의 소유물. 이라고 해석하는게 좀 더 나을 것 같아요.
Central Chief의 경우 뭐라 번역해야할지 애매하네요...
중심 되는 족장이니 대족장 정도로 해석해도 될 것 같네요.  개인적인 의견입니다 ㅎ

**Comment by creamizzing** [comment]
제가 얼마전에 '내 문장이 그렇게 이상한가요?'를 읽었는데 적,의,것,들에 대해 써 있었거든요
문장을 의 한번 빼고 넣고 번역해봤는데 없는 게 낫더라구요.

**Comment by creamizzing** [comment]
jine0th님 도움으로 막혔던 항목 번역 완료 했습니다. 감사합니다.
