### ISSUE TITLE
번역 작업 시작하기

### ISSUE THREAD

**Issue by goldmetal** [StonehearthForum/stoneHearth_locale_kr#4]
알파21 팀 작업이 시작되었습니다.
깃허브가 처음이신분은 아래와 같은 방법으로 진행하시면 됩니다.

## **[ 레포 내려 받기 ]**
- 1. 깃허브 데스크탑을 켭니다. (없다면 여기를...https://desktop.github.com/)
- 2. 왼쪽 상단에 + 을 클릭.
- 3. 우리 팀 이름을 선택하면 **stoneHearth_locale_kr** 레포가 있습니다.
- 4. 레포를 선택하고 저장할 경로를 선택하여 내려 받습니다.

## **[ 번역 작업 하기 ]**
- 5. 번역 데이터 도구 TranslateHelper 을 엽니다.
       (없다면 여기를...http://cafe.naver.com/stonehearth/669)
- 6. 첫번째 Browse 버튼으로 원본 파일을 선택합니다.
      원본 텍스트 파일은 **untranslations/stonehearth.json**입니다. 
- 7. 두번째 Browse 버튼으로 번역 중인 파일을 선택합니다.
      현재 번역된 파일은 **translations/stonehearth/ko.json**입니다.
- 8. 두 파일이 자동 비교 되어 나타납니다.
- 9. 노란색 칸으로 된 데이터의 맨 오른쪽 (Trans) 데이터를 번역해주면 됩니다.
- 10. 번역 작업을 마치면 Save 버튼으로 ko.json을 업데이트 해주면 됩니다.

**_#.최초 이후부터의 번역 작업은 시작하시기 전에 꼭!
     Sync 버튼을 눌러서 번역본을 업데이트하세요._**

**_#.번역 시에 프로젝트에서 용어,단어 규칙을 확인 & 공유하세요. 
         https://github.com/StonehearthForum/stoneHearth_locale_kr/projects/1_**

## **[ 번역 확인 하기 ]**
- 11. stoneHearth_locale_kr을 zip으로 압축합니다.
- 12. 확장명을 smod로 바꾸어줍니다.
       (확장명이 보이지 않으면 윈도우 제어판 - 폴더 옵션에서 풀어줍니다.)
- 13. **steam 경로/steamapp / common / Stonehearth / mods** 에 넣어줍니다. 
        (이 폴더는 바로가기 만들어서 stoneHearth_locale_kr 폴더 옆에 두면 편합니다.)
- 14. 게임을 켜고 번역된 곳을 확인해봅니다.
- 15. 게임이 정상적으로 돌아가면 오케이. 번역 작업이 완료되었습니다.

## **[ 레포 올리기 ]**
- 16. 다시 깃허브 데스크탑으로 돌아옵니다.
- 17. 번역하면서 파일 내용을 바꿨으므로 Change 목록이 생겨난 것을 확인할 수 있습니다.
- 18. 아래에 Summary / Description 에 각각 제목 / 설명을 기입합니다.
        (설명에는 변경한 내용을 간단히 적습니다.)
- 19. 맨 아래의 **Commit to Alpha21**을 눌러 커밋합니다.
- 20. 오른쪽 상단에 회전화살표가 있는 **Sync**를 눌러 레포와 동기화시킵니다.
- 21. 업데이트 된 내용은 깃허브 홈페이지에서 확인 가능합니다.

**Comment by ghost** [comment]
바로 커밋하기 보단 PR을 거치는 게 좋을 꺼 같아요.

**Comment by Goldmetal** [comment]
그럼 현지화 팀은 PR로만 할 수 있게 하는 방법이 있나요? 그게 더 안전할거 같네요.

**Comment by goldmetal** [comment]
잘 몰라서 그런데 PR은 머지할 때 쓰이는거 아닌가요

**Comment by ghost** [comment]
merge할때 쓰는게 맞긴한데 깃헙에서는 검수용으로도 사용할 수 있습니다.
