### ISSUE TITLE
질문 있습니다.

### ISSUE THREAD

**Issue by jine0th** [StonehearthForum/stoneHearth_locale_kr#6]
안녕하세요.

다름이 아니라 팀원 간에 번역 작업 겹치면 안되니 자신이 번역할 범위을 코멘트로 알려달라고 하셨는데

제가 무작정 일단 번역했던 것 같습니다.

삭제하거나 수정하려고 해도 아직 사용방법이 익숙치 않아헷갈리네요.

내일 제가 다시 세세히 확인해보려고 합니다.

혹시 제가 여태 했던 작업들이 잘못된 경우에 삭제하고 번역 범위를 설정하고 다시 하려고 하는데

아무리 찾아봐도 방법을 모르겠네요 ㅠ

암튼 내일 다시 확인해보도록 하겠습니다... 공지를 잘 읽지 못해 죄송합니다. 잘 지키도록 하겠습니다!!!

**Comment by goldmetal** [comment]
번역된 내용을 다시 삭제하려면 Reset 버튼을 누르면 됩니다.
그럼 원본 영문 문장이 들어가면서 원상복귀 되지요.

하고싶으신 노랑색 영역의 Tag (첫번째 열) 의 3레벨까지만
# 5  이슈에 말씀해주시면 됩니다.

저도 번역팀을 처음 꾸려보는거라 안내가 미흡할 수 있으니
이점 양해부탁드립니다.

P.s
Graphs-Network 살펴보니 Fork를 안하셨더군요.
이미 이쪽 레포를 받아두셨다면 다른 곳에 옮겨두시고 (작업하셨다고 하니..)
# 4 번 공지 참고하시어 Fork로 자신의 계정에 레포를 복사하시고
그 레포에서 작업해주세요.

**Comment by ghost** [comment]
추가적으로 궁금하신 사항이 없다면 close 해주시고 질문사항이 존재한다면 아래에 코멘트로 남겨주세요
