### ISSUE TITLE
이번 remote 4e700e4 커밋 문제 있는건가요?

### ISSUE THREAD

**Issue by goldmetal** [StonehearthForum/stoneHearth_locale_kr#9]
4e700e4 번 커밋보니까 마이크레이션 되기 전 소스 긁어오던데
특별히 문제가 없는건지요?

**Comment by ghost** [comment]
이게 왜 이렇게 나왔는지 저도 잘 모르겠네요.., revert하는 쪽이 좋을 꺼 같습니다

**Comment by goldmetal** [comment]
33wkdgns님의 다음 커밋 상태를 보고 생각해보도록 해요.
영향 받은 파일 보니까 지금 우리가 사용하고 있는 파일은 아니던데..
translation 폴더에서 ko.json 외의 파일은 지워도 되지 않을까요?

**Comment by ghost** [comment]
네 지워도 문제없습니다.

**Comment by goldmetal** [comment]
넵, 그럼 33wkdgns님 다음 커밋을 확인해보고
더 이상 remote가 없다면 해당파일은 지울께요.
